TrajectoryPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.3
  min_vel_x: 0.05
  
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  
  acc_lim_theta: 2.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 10.0

  # Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Differential-drive robot configuration
  holonomic_robot: false