obstacle_range: 5.5
raytrace_range: 6.0

footprint: [[-0.2, -0.175], [-0.2, 0.175], [0.2, 0.175], [0.2, -0.175]]
#robot_radius: 0.22  # Use footprint instead

inflation_radius: 0.4
cost_scaling_factor: 3.0

map_type: costmap

observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: laser_frame
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true